create database Address_Book_Service;
use Address_Book_Service;
show databases;
select database();
show tables;
create table contacts(id int primary key auto_increment, firstname varchar(20), lastname varchar(20), address varchar(60), city varchar(20), state varchar(30), zip int, phone_no long, email varchar(160)); 
describe contacts;
insert into contacts(firstname, lastname, address, city, state, zip, phone_no, email) values ('vikash', 'pathak', 'Garden', 'Mumbra', 'Maha', 400612, 7738565536, 're@gmail.com'),('rahul','pathak','Wadi','Mumbai','Maha',4000003, 9819585533, 'zd@gmail.com');
select * from address_book;
update address_book set lastname = 'mishra' where firstname = 'rahul';
insert into contacts(firstname, lastname, address, city, state, zip, phone_no, email) values ('ravi', 'Shah', 'Hadge', 'Mumbai', 'Maha', 402512, 9787565536, 'rsm@gmail.com');
delete from address_book where firstname = 'Alina';
select firstname, lastname, address, city, state, zip, phone_no, email from address_book where city = 'Mumbra';
select firstname, lastname, address, city, state, zip, phone_no, email from address_book where state = 'maha';
select city , count(city) from address_book group by city;
select state , count(state) from address_book group by state;
select * from address_book where city = 'Mumbai' order by firstname;
alter table address_book add type varchar(50);
alter table My_Book rename to Contact_Book;
describe Contact_Book;
update my_book set type = 'Family' where firstname = 'vikash';
select * from Contact_book;
update my_book set type = 'Family' where firstname = 'rahul';
update my_book set type = 'Profession' where firstname = 'Alina';
select type , count(type) from my_book group by type;
alter table Contact_Book drop column type;
create table Address_Book(id int primary key auto_increment, type varchar(20));
describe Address_Book;
insert into  contact_types(contact_type) values ('Freind');
select * from contact_types;
drop table address_book;
create table contact_types(id int primary key auto_increment, contact_type varchar(20));
describe Address_Book;
select * from contacts;
insert into type (type) values ('Freinds');
insert into contacts(firstname, lastname, address, city, state, zip, phone_no, email) values ('Sharmin', 'Sayed', 'Khadi', 'Mumbai', 'Maha', 400103, 7738565536, 'rsm@gmail.com');
alter table contact_book drop column typeId;
drop table contact_book;
drop table type;
alter table contacts add (contact_typeId int, foreign key(contact_typeId) references contact_types(id)); 
update contacts set contact_typeId = 3 where firstname = 'ravi';
select contacts.firstname, contact_types.contact_type from contacts , contact_types where contacts.contact_typeId = contact_types.id;